#usamos como sistema operativo ubuntu con la versión 20.10
FROM ubuntu:20.10

#indicamos información sobre quién es la persona encargada del contenedor
LABEL maintainer="Irene Cano Jerez"

#creamos un usuario y una carpeta sobre la que tendrá permisos
RUN groupadd grupo && useradd --gid grupo --shell /bin/bash --create-home usuario && mkdir /idiomas && chown -R usuario /idiomas

#permisos necesarios para el usuario e instalación de node y npm en alpine
RUN mkdir /idiomas/node_modules && chown -R usuario /idiomas/node_modules && apt-get update && apt install -y nodejs && apt-get install -y npm
#usuario sin privilegios
USER usuario

#copiamos el fichero de dependencias
COPY package.json ./idiomas/

#instalamos las dependencias y borramos el fichero de dependencias una vez éstas han sido instaladas
RUN cd idiomas && npm install && rm package.json

#variable de entorno para gestionar node_modules
ENV PATH=/idiomas/node_modules/.bin:$PATH

#creamos el directorio de trabajo /test
WORKDIR /test

#ejecutamos los tests con grunt, en concreto, con el comando 'grunt test'
CMD ["grunt","test"]
